package schedule;

public enum Department {
    /** Department abbreviations as per Berkeley Academic Guide.
     *  NOTE: Spaces and commas removed in enum. L&S -> LS
     *  @source http://guide.berkeley.edu/courses/
     */

    AEROSPC, AFRICAM, ARESEC, AMERSTD, AHMA, ANTHRO, AST, ARABIC, ARCH, ARMENI, HISTART, ART,
    HUM, ASAMST, ASIANST, ASTRON, BANGLA, BIBLIOG, BIOENG, BIOLOGY, BIOPHY, BOSCRSR, BUDDSTD,
    BULGARI, BURMESE, EWMBDA, XMBA, MBA, PHDBA, UGBA, CATALAN, CELTIC, CHMENG, CHEM, CHICANO,
    CHINESE, CYPLAN, CIVENG, CLASSIC, COGSCI, COLWRIT, COMPBIO, COMLIT, CMPBIO, COMPSCI,
    CRWRIT, CRITTH, CUNEIF, CZECH, DANISH, DATASCI, DEMOG, DESINV, DEVENG, DEVP, DEVSTD,
    DIGHUM, DUTCH, EPS, EALANG, ECON, EDUC, EGYPT, EECS, ELENG, ENERES, ENGIN, ENGLISH,
    ENVDES, ENVECON, ESPM, ENVSCI, ETHSTD, EUST, FILIPN, FILM, MFE, FINNISH, FOLKLOR, FRENCH,
    GWS, GEOG, GERMAN, GMS, GPP, GLOBAL, GSPDP, GREEK, HMEDSCI, HEBREW, HINDI, HISTORY,
    HUNGARI, ICELAND, ILA, INDONES, INDENG, CYBER, INFO, INTEGBI, ISF, IAS, IRANIAN, ITALIAN,
    JAPAN, JEWISH, JOURN, KHMER, KOREAN, LDARCH, LANPRO, LATAMST, LATIN, LEGALST, LGBT, LS,
    LINFOST, LINGUIS, MATSCI, MATH, MECENG, MEDIAST, MEDST, MESTU, MILAFF, MILSCI, MCELLBI,
    MONGOLN, MUSIC, NSE, NATAMST, NATRES, NAVSCI, NESTUD, NEUROSC, NWMEDIA, NORWEGN, NUCENG,
    NUSCTX, OPTOM, PACS, PERSIAN, PHILOS, PHYSED, PHYSICS, PLANTBI, POLISH, POLECON, POLSCI,
    PORTUG, PSYCH, PUBAFF, PBHLTH, PUBPOL, PUNJABI, RDEV, RHETOR, RUSSIAN, SANSKR, SCANDIN,
    SCMATHE, STS, SEMITIC, SLAVIC, SOCWEL, SOCIOL, SSEASN, SASIAN, SEASIAN, SPANISH, EDUCSPE,
    STAT, SWEDISH, TAMIL, TELUGU, THAI, THEATER, TIBETAN, TURKISH, UGIS, URDU, VIETNMS,
    VISSCI, VISSTD, YIDDISH
}
